export const VOICE_DOCUMENT_DRAFTING_TOOL_ACK =
  "IN_PROGRESS";

export const VOICE_DOCUMENT_COMPLETED_TOOL_ACK =
  "COMPLETED";

/** @deprecated Use {@link VOICE_DOCUMENT_DRAFTING_TOOL_ACK} for tool responses. */
export const VOICE_DOCUMENT_SAVED_TOOL_ACK = VOICE_DOCUMENT_DRAFTING_TOOL_ACK;
