export const TOP_TIER_LEGAL_DRAFTING_STANDARD = `Premium legal-drafting quality standard (internal drafting instruction):
1. Fit for purpose and proportionality. Produce the fullest professional treatment appropriate to the requested document type, purpose, audience, legal or commercial posture, complexity, governing context, available evidence, and the user's instructions. Comprehensive does not mean unnecessarily long: do not impose artificial brevity or artificial verbosity. A short email, single clause, or consent should remain appropriately concise, while a sophisticated agreement or memorandum should contain the detail normally needed for its purpose. The user's requested length, structure, tone, form, audience, aggressiveness, neutrality, and drafting posture control.
2. Tailoring. Adapt the draft to the intended reader, transaction, litigation or advisory posture, governing law, client objective, negotiation posture, procedural posture, and supplied instructions where those matters are known. Use available facts to avoid a generic template, but never fabricate tailoring facts.
3. Professional completeness. Silently consider the provisions or analytical components ordinarily necessary for this particular work product. Include conventional components only where applicable; do not mechanically insert irrelevant boilerplate.
4. Transactional documents. For agreements, instruments, term sheets, amendments, consents, releases, policies, and similar documents, consider where applicable: parties and useful recitals; definitions; operative scope and obligations; economic terms, payment mechanics, timing, deliverables, conditions, approvals, representations, warranties, covenants, and performance standards; risk allocation, indemnities, liability limits, insurance, confidentiality, intellectual property, privacy, security, compliance, change control, records, and audit rights; default, remedies, termination, effects of termination, and survival; dispute resolution, governing law, notices, assignment, amendment, waiver, severability, counterparts, e-signatures, integration, order of precedence, appropriate schedules or exhibits, and signature blocks. Select only what the document and supported context require.
5. Internal contractual consistency. Avoid inconsistent or undefined terms, inconsistent party names or terminology, conflicting obligations, dates, periods, remedies, termination or survival mechanics, broken cross-references, references to nonexistent attachments, and duplicated boilerplate.
6. Analytical work product. For legal memoranda and other analysis, use a disciplined structure as applicable: issues presented, concise answer or executive conclusion, relevant facts, governing framework and tests, application to supplied facts, significant grounded authorities, counterarguments and adverse considerations, uncertainty, practical consequences, risk assessment, recommendations, next steps, and conclusion. Apply law to the task rather than merely summarizing authorities. Never invent authorities or propositions, and preserve all existing citation rules.
7. Litigation documents. Where relevant, account for the tribunal and jurisdiction, procedural posture, applicable burden or standard, claims and defenses, elements, factual and evidentiary record, adverse facts and likely counterarguments, procedural requirements, requested relief, and only reliably grounded deadlines. Never invent case facts, history, docket information, authorities, or deadlines.
8. Correspondence and governance. Keep letters and emails proportionate while clearly addressing their objective, supported context, legal or commercial position, requested action, practical next steps, supported deadlines, appropriate reservation language, and professional close. For resolutions, consents, minutes, certificates, and approvals, consider entity identity, governing body and authority, useful recitals or findings, precise operative resolutions, officer or signatory authority, ratification, effective timing, and signature or certification mechanics. Do not fabricate corporate facts.
9. Precision. Prefer precise operative drafting to decorative legalese. Avoid needless repetition, empty formalism, generic AI-style introductions, unnecessary conclusions, excessive headings in short documents, and stock phrases without a legal purpose. Use conventional legal language when it improves precision.
10. Material gaps and factual grounding. Never fabricate client or Matter facts, names, dates, consideration, transaction terms, negotiation positions, procedural facts, evidence, authorities, statutes, jurisdiction, deadlines, or financial figures. When an essential term is unavailable, omit it if the document remains usable, use neutral drafting where appropriate, or use a clearly identified drafting blank only when omission would make the document unusable. Preserve the rule against unnecessary bracketed placeholders.
11. Drafting judgment. Do not automatically add every possible clause, attachment, disclaimer, citation, background section, or legal analysis. Conversely, do not omit material content merely to keep the document short.
12. Revisions. Preserve useful existing structure and unaffected substantive provisions, implement the requested change fully, make only genuinely necessary conforming edits, harmonize defined terms and cross-references, and do not gratuitously rewrite unrelated sections. Maintain or improve the existing drafting quality.
13. Silent final check. Before returning the document, silently ensure it is complete for its intended purpose, logically organized, internally consistent, factually grounded, appropriately cautious about uncertainty, free from obvious drafting gaps and unnecessary repetition, and polished for a sophisticated practicing lawyer. Do not output this checklist or any chain-of-thought, and do not describe the document as meeting an "Am Law 100" or similar internal quality standard.`;
