import React, { useMemo, useState } from "react";
import { Briefcase, Grid2X2, List, Plus, Search } from "lucide-react";
import { Case, Document } from "../types";

interface Props { matters: Case[]; onRefresh: () => Promise<void> | void; onOpenMatter: (id: string) => void; }
type Sort = "activity" | "created" | "name";

export default function MattersView({ matters, onRefresh, onOpenMatter }: Props) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<Sort>("activity");
  const [view, setView] = useState<"cards" | "list">("cards"); const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [clientName, setClientName] = useState("");
  const [note, setNote] = useState(""); const [documentTitle, setDocumentTitle] = useState(""); const [documentText, setDocumentText] = useState("");
  const [library, setLibrary] = useState<Document[]>([]); const [selectedLibrary, setSelectedLibrary] = useState<string[]>([]); const [saving, setSaving] = useState(false);

  const shown = useMemo(() => matters.filter((matter) => `${matter.name} ${matter.client_name || ""}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => {
    if (sort === "name") return a.name.localeCompare(b.name);
    const field = sort === "created" ? "created_at" : "last_activity_at";
    return new Date((b[field] || b.created_at) as string).getTime() - new Date((a[field] || a.created_at) as string).getTime();
  }), [matters, query, sort]);

  const openCreate = async () => { const response = await fetch("/api/documents?caseId=null"); setLibrary(response.ok ? await response.json() : []); setShowCreate(true); };
  const reset = () => { setName(""); setDescription(""); setClientName(""); setNote(""); setDocumentTitle(""); setDocumentText(""); setSelectedLibrary([]); };
  const create = async (event: React.FormEvent) => {
    event.preventDefault(); const hasDocument = documentTitle.trim() && documentText.trim();
    if (!name.trim() || !description.trim() || (!note.trim() && !hasDocument && selectedLibrary.length === 0)) return;
    setSaving(true);
    try {
      const response = await fetch("/api/cases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, clientName, startingNote: note, startingDocument: hasDocument ? { title: documentTitle, text: documentText } : null, libraryDocumentIds: selectedLibrary }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Matter could not be created");
      await onRefresh(); setShowCreate(false); reset(); onOpenMatter(data.id);
    } catch (error) { alert(error instanceof Error ? error.message : "Matter could not be created"); } finally { setSaving(false); }
  };

  return <div className="flex-1 h-full overflow-y-auto bg-white p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Briefcase className="h-5 w-5" /><h2 className="text-lg font-bold uppercase">Matters</h2></div><p className="mt-1 text-[11px] font-mono uppercase text-zinc-400">Matter workspaces and assignments</p></div><button onClick={() => void openCreate()} className="flex items-center gap-2 rounded bg-zinc-950 px-4 py-2 text-[10px] font-mono font-bold uppercase text-white"><Plus className="h-4 w-4" />Create Matter</button></header>
    <div className="flex flex-wrap gap-2 rounded border border-zinc-200 bg-zinc-50 p-3"><div className="flex min-w-64 flex-1 items-center gap-2 rounded border bg-white px-3"><Search className="h-4 w-4 text-zinc-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full py-2 text-xs outline-none" placeholder="Search Matter name or client" /></div><select value={sort} onChange={(e) => setSort(e.target.value as Sort)} className="rounded border border-zinc-300 bg-white px-3 text-[10px] font-mono uppercase"><option value="activity">Last activity</option><option value="created">Created date</option><option value="name">Name</option></select><button onClick={() => setView("cards")} className={`rounded border p-2 ${view === "cards" ? "bg-zinc-900 text-white" : "bg-white"}`}><Grid2X2 className="h-4 w-4" /></button><button onClick={() => setView("list")} className={`rounded border p-2 ${view === "list" ? "bg-zinc-900 text-white" : "bg-white"}`}><List className="h-4 w-4" /></button></div>
    {shown.length === 0 ? <div className="rounded border border-dashed p-16 text-center text-xs text-zinc-500">No Matters match this view.</div> : view === "cards" ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shown.map((m) => <button key={m.id} onClick={() => onOpenMatter(m.id)} className="rounded border border-zinc-200 p-5 text-left hover:border-zinc-900"><div className="flex justify-between gap-3"><h3 className="text-sm font-semibold">{m.name}</h3><Status value={m.status || "Open"} /></div>{m.client_name && <p className="mt-2 text-xs text-zinc-600">{m.client_name}</p>}<p className="mt-4 text-[9px] font-mono uppercase text-zinc-400">Last activity {new Date(m.last_activity_at || m.created_at).toLocaleDateString()}</p></button>)}</div> : <div className="overflow-hidden rounded border border-zinc-200"><div className="grid grid-cols-[2fr_1.2fr_1fr_1.2fr_1fr_1fr] gap-3 bg-zinc-50 px-4 py-3 text-[9px] font-mono font-bold uppercase text-zinc-500"><span>Matter</span><span>Client</span><span>Status</span><span>Practice area</span><span>Last activity</span><span>Created</span></div>{shown.map((m) => <button key={m.id} onClick={() => onOpenMatter(m.id)} className="grid w-full grid-cols-[2fr_1.2fr_1fr_1.2fr_1fr_1fr] gap-3 border-t px-4 py-3 text-left text-xs hover:bg-zinc-50"><strong>{m.name}</strong><span>{m.client_name || "—"}</span><Status value={m.status || "Open"} /><span>{m.matter_type || "—"}</span><span>{new Date(m.last_activity_at || m.created_at).toLocaleDateString()}</span><span>{new Date(m.created_at).toLocaleDateString()}</span></button>)}</div>}
  </div>{showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-5"><form onSubmit={create} className="max-h-[92vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded border border-zinc-300 bg-white p-6 shadow-xl"><div><h3 className="text-sm font-semibold uppercase">Create Matter</h3><p className="mt-1 text-xs text-zinc-500">Add an assignment and at least one starting input.</p></div><div className="grid gap-3 md:grid-cols-2"><Input label="Matter name *" value={name} onChange={setName} /><Input label="Client name" value={clientName} onChange={setClientName} /></div><label className="block text-[10px] font-mono font-bold uppercase text-zinc-500">Assignment description *<textarea value={description} onChange={(e) => setDescription(e.target.value)} className="mt-1 h-24 w-full rounded border px-3 py-2 text-xs font-sans font-normal normal-case" /></label><label className="block text-[10px] font-mono font-bold uppercase text-zinc-500">Starting instruction or note<textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-1 h-20 w-full rounded border px-3 py-2 text-xs font-sans font-normal normal-case" /></label><div className="grid gap-3 md:grid-cols-2"><Input label="Starting document title" value={documentTitle} onChange={setDocumentTitle} /><label className="text-[10px] font-mono font-bold uppercase text-zinc-500">Document text<textarea value={documentText} onChange={(e) => setDocumentText(e.target.value)} className="mt-1 h-24 w-full rounded border px-3 py-2 text-xs font-sans font-normal normal-case" /></label></div>{library.length > 0 && <fieldset className="rounded border p-3"><legend className="px-1 text-[10px] font-mono font-bold uppercase text-zinc-500">Select Firm Library documents</legend><div className="max-h-32 space-y-2 overflow-y-auto">{library.map((d) => <label key={d.id} className="flex gap-2 text-xs"><input type="checkbox" checked={selectedLibrary.includes(d.id)} onChange={(e) => setSelectedLibrary((x) => e.target.checked ? [...x, d.id] : x.filter((id) => id !== d.id))} />{d.title}</label>)}</div></fieldset>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded border px-4 py-2 text-[10px] font-mono uppercase">Cancel</button><button disabled={saving || !name.trim() || !description.trim() || (!note.trim() && !(documentTitle.trim() && documentText.trim()) && selectedLibrary.length === 0)} className="rounded bg-zinc-950 px-4 py-2 text-[10px] font-mono font-bold uppercase text-white disabled:opacity-40">{saving ? "Creating…" : "Create Matter"}</button></div></form></div>}</div>;
}

function Status({ value }: { value: string }) { return <span className="h-fit rounded border border-zinc-300 px-2 py-1 text-[9px] font-mono uppercase">{value}</span>; }
function Input({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-[10px] font-mono font-bold uppercase text-zinc-500">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded border px-3 py-2 text-xs font-sans font-normal normal-case" /></label>; }
