import React, { useEffect, useState } from "react";
import { AlertTriangle, Edit, RefreshCw, Save, Sparkles } from "lucide-react";
import { MatterIntelligenceRecord } from "../types";

export default function MatterIntelligence({ matterId }: { matterId: string }) {
  const [record, setRecord] = useState<MatterIntelligenceRecord | null>(null), [content, setContent] = useState(""), [editing, setEditing] = useState(false), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false);
  const load = async () => { const response = await fetch(`/api/cases/${matterId}/intelligence`); if (response.ok) { const data = await response.json(); setRecord(data); setContent(data?.content || ""); } setLoaded(true); };
  useEffect(() => { void load(); }, [matterId]);
  const generate = async () => { if (record && !confirm("Regenerate Matter Intelligence using the current active Sources?")) return; setBusy(true); try { const response = await fetch(`/api/cases/${matterId}/intelligence/generate`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw Error(data.error || "Generation failed"); setRecord(data); setContent(data.content); setEditing(false); } catch (e) { alert(e instanceof Error ? e.message : "Generation failed"); } finally { setBusy(false); } };
  const save = async () => { if (!record || !content.trim()) return; setBusy(true); try { const response = await fetch(`/api/cases/${matterId}/intelligence`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); const data = await response.json(); if (!response.ok) throw Error(data.error || "Save failed"); setRecord({ ...data, sources_changed: record.sources_changed }); setEditing(false); } catch (e) { alert(e instanceof Error ? e.message : "Save failed"); } finally { setBusy(false); } };
  if (!loaded) return <p className="py-16 text-center text-xs font-mono uppercase text-zinc-400">Loading Matter Intelligence…</p>;
  if (!record) return <div className="mx-auto max-w-2xl rounded border border-dashed p-16 text-center"><Sparkles className="mx-auto mb-4 h-8 w-8 text-zinc-300" /><h3 className="text-sm font-semibold uppercase">Matter Intelligence</h3><p className="mx-auto mt-2 max-w-md text-xs leading-relaxed text-zinc-500">Generate a source-backed working analysis only when you are ready. AI-generated content requires lawyer review.</p><button onClick={() => void generate()} disabled={busy} className="mt-6 rounded bg-zinc-950 px-5 py-2.5 text-[10px] font-mono font-bold uppercase text-white disabled:opacity-50">{busy ? "Generating…" : "Generate Matter Intelligence"}</button></div>;
  return <div className="mx-auto max-w-4xl space-y-4"><div className="rounded border border-zinc-300 bg-zinc-50 p-3 text-xs"><strong>Lawyer review required.</strong> Matter Intelligence is AI-generated from active Matter Sources and may contain errors or omissions.</div>{record.sources_changed && <div className="flex items-center gap-2 rounded border border-zinc-300 p-3 text-xs"><AlertTriangle className="h-4 w-4" /><strong>Sources have changed since this Matter Intelligence was generated.</strong></div>}<header className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold uppercase">Matter Intelligence</h3><p className="mt-1 text-[9px] font-mono uppercase text-zinc-400">Generated {new Date(record.generated_at).toLocaleString()} · Edited {new Date(record.last_edited_at).toLocaleString()} · Internal version {record.version}</p></div><div className="flex gap-2">{editing ? <button onClick={() => void save()} disabled={busy} className="flex items-center gap-1 rounded bg-zinc-950 px-4 py-2 text-[10px] font-mono font-bold uppercase text-white"><Save className="h-3.5 w-3.5" />Save</button> : <button onClick={() => setEditing(true)} className="flex items-center gap-1 rounded border px-4 py-2 text-[10px] font-mono font-bold uppercase"><Edit className="h-3.5 w-3.5" />Edit</button>}<button onClick={() => void generate()} disabled={busy} className="flex items-center gap-1 rounded border px-4 py-2 text-[10px] font-mono font-bold uppercase"><RefreshCw className={`h-3.5 w-3.5 ${busy ? "animate-spin" : ""}`} />Regenerate</button></div></header>{editing ? <textarea value={content} onChange={(e) => setContent(e.target.value)} className="min-h-[650px] w-full rounded border p-6 font-mono text-sm leading-relaxed" /> : <article className="min-h-[500px] whitespace-pre-wrap rounded border border-zinc-200 p-8 text-sm leading-relaxed text-zinc-800">{content}</article>}</div>;
}
