import React, { useEffect, useState } from "react";
import { Case } from "../types";

export default function MatterOverview({ matter, onChange }: { matter: Case; onChange: (matter: Case) => void }) {
  const [form, setForm] = useState(matter); const [saving, setSaving] = useState(false);
  useEffect(() => setForm(matter), [matter]);
  const set = (key: keyof Case, value: string | boolean | null) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); try { const response = await fetch(`/api/cases/${matter.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw Error(data.error); onChange(data); } catch (e) { alert(e instanceof Error ? e.message : "Matter could not be saved"); } finally { setSaving(false); } };
  const suggestion = (field: "matter_type" | "jurisdiction" | "preliminary_objectives", flag: "matter_type_suggested" | "jurisdiction_suggested" | "objectives_suggested") => Boolean(form[flag]) && form[field] ? <div className="mt-2 flex items-center gap-2 text-[9px] font-mono uppercase"><span className="rounded bg-zinc-100 px-2 py-1">AI suggested</span><button onClick={() => set(flag, false)} className="underline">Confirm</button><button onClick={() => { set(field, null); set(flag, false); }} className="underline">Remove</button></div> : null;
  return <div className="mx-auto max-w-3xl space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Matter name" value={form.name} onChange={(v) => set("name", v)} /><Field label="Client" value={form.client_name || ""} onChange={(v) => set("client_name", v)} /><Field label="Matter type or practice area" value={form.matter_type || ""} onChange={(v) => { set("matter_type", v); set("matter_type_suggested", false); }} extra={suggestion("matter_type", "matter_type_suggested")} /><Field label="Jurisdiction" value={form.jurisdiction || ""} onChange={(v) => { set("jurisdiction", v); set("jurisdiction_suggested", false); }} extra={suggestion("jurisdiction", "jurisdiction_suggested")} /><label className="md:col-span-2 text-[10px] font-mono font-bold uppercase text-zinc-500">Preliminary objectives<textarea value={form.preliminary_objectives || ""} onChange={(e) => { set("preliminary_objectives", e.target.value); set("objectives_suggested", false); }} className="mt-1 h-28 w-full rounded border px-3 py-2 text-sm font-sans font-normal normal-case" />{suggestion("preliminary_objectives", "objectives_suggested")}</label><label className="text-[10px] font-mono font-bold uppercase text-zinc-500">Status<select value={form.status || "Open"} onChange={(e) => set("status", e.target.value)} className="mt-1 w-full rounded border bg-white px-3 py-2 text-sm font-sans font-normal normal-case"><option>Open</option><option>Waiting for Client</option><option>On Hold</option><option>Closed</option></select></label></div><button onClick={() => void save()} disabled={saving} className="rounded bg-zinc-950 px-4 py-2 text-[10px] font-mono font-bold uppercase text-white">{saving ? "Saving…" : "Save Overview"}</button></div>;
}
function Field({ label, value, onChange, extra }: { label: string; value: string; onChange: (value: string) => void; extra?: React.ReactNode }) { return <label className="text-[10px] font-mono font-bold uppercase text-zinc-500">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded border px-3 py-2 text-sm font-sans font-normal normal-case" />{extra}</label>; }
